// Code generated by protoc-gen-go.
// source: addressbook.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto

It has these top-level messages:
	Person
	AddressBook
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto1.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name   string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id     int32                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email  string                `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto1.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=proto.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto1.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto1.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto1.RegisterType((*Person)(nil), "proto.Person")
	proto1.RegisterType((*Person_PhoneNumber)(nil), "proto.Person.PhoneNumber")
	proto1.RegisterType((*AddressBook)(nil), "proto.AddressBook")
	proto1.RegisterEnum("proto.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto1.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0xd1, 0x4a, 0xc3, 0x40,
	0x10, 0xf4, 0xd2, 0xe4, 0xb0, 0x1b, 0x2c, 0x71, 0x11, 0x8d, 0x3e, 0x85, 0x80, 0x10, 0x28, 0x04,
	0xac, 0xfe, 0x80, 0x85, 0x82, 0xa2, 0x35, 0xe5, 0x10, 0x7c, 0x4e, 0xc8, 0x82, 0xa1, 0x4d, 0xf6,
	0x48, 0xea, 0x43, 0x7f, 0xdc, 0x67, 0xc9, 0xdd, 0x21, 0x0a, 0x7d, 0xba, 0xd9, 0xd9, 0x61, 0xe6,
	0x66, 0xe1, 0xbc, 0xac, 0xeb, 0x9e, 0x86, 0xa1, 0x62, 0xde, 0xe6, 0xba, 0xe7, 0x3d, 0x63, 0x60,
	0x9e, 0xf4, 0x5b, 0x80, 0xdc, 0x50, 0x3f, 0x70, 0x87, 0x08, 0x7e, 0x57, 0xb6, 0x14, 0x8b, 0x44,
	0x64, 0x53, 0x65, 0x30, 0xce, 0xc0, 0x6b, 0xea, 0xd8, 0x4b, 0x44, 0x16, 0x28, 0xaf, 0xa9, 0xf1,
	0x02, 0x02, 0x6a, 0xcb, 0x66, 0x17, 0x4f, 0x8c, 0xc8, 0x0e, 0x78, 0x07, 0x52, 0x7f, 0x72, 0x47,
	0x43, 0xec, 0x27, 0x93, 0x2c, 0x5c, 0x5c, 0xdb, 0x8c, 0xdc, 0x1a, 0xe7, 0x9b, 0x71, 0xf7, 0xf6,
	0xd5, 0x56, 0xd4, 0x2b, 0x27, 0xbc, 0x51, 0x10, 0xfe, 0xa1, 0xf1, 0x12, 0x64, 0x67, 0x90, 0x4b,
	0x77, 0x13, 0xce, 0xc1, 0xdf, 0x1f, 0x34, 0x99, 0x1f, 0xcc, 0x16, 0x57, 0x47, 0x7c, 0xdf, 0x0f,
	0x9a, 0x94, 0x11, 0xa5, 0x73, 0x98, 0xfe, 0x52, 0x08, 0x20, 0xd7, 0xc5, 0xf2, 0xf9, 0x75, 0x15,
	0x9d, 0xe0, 0x29, 0xf8, 0x4f, 0xc5, 0x7a, 0x15, 0x89, 0x11, 0x7d, 0x14, 0xea, 0x25, 0xf2, 0xd2,
	0x07, 0x08, 0x1f, 0xed, 0x51, 0x96, 0xcc, 0x5b, 0xbc, 0x05, 0xa9, 0x89, 0xf5, 0x6e, 0xac, 0x3f,
	0x56, 0x38, 0xfb, 0x17, 0xa5, 0xdc, 0xb2, 0x92, 0x86, 0xbd, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xde, 0x74, 0xfe, 0x62, 0x51, 0x01, 0x00, 0x00,
}
